theme: jekyll-theme-minimal

title: Belegt
description: Model train track occupation sensor
logo: https://github.com/eurovibes/dcclicht/raw/master/images/belegt.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
